title: David Alvear G.
description: > # this means to ignore newlines until "baseurl:"
  David Alvear's Web Page, enjoy it :).
permalink: ':title/'
baseurl: "/dfalveargOT.github.io" # the subpath of your site, e.g. /blog
url: "https://dfalveargot.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: David Felipe Alvear Goyes # add your name
author-img: David-Alvear.png # add your photo
about-author: I am a Physics Engineer student, National University of Colombia. Explore and enjoy. # add description
social-twitter: Dfalvearg # add your Twitter handle
social-facebook: felipe.rocket # add your Facebook handle
social-github: dfalveargOT # add your Github handle
social-linkedin: dfalvearg@unal.edu.co # add your Linkedin handle
social-email: dfalvearg@unal.edu.co # add your Email address

# Disqus
discus-identifier: mr-ddvid # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
